name: Update version

on:
  workflow_dispatch:
    inputs:
      libraryVersion:
        description: 'LexActivator Library Version'
        required: true
        default: ''
      packageVersion:
        description: 'Package Version'
        required: true
        default: ''

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create new branch
        run: git checkout -b release/${{ github.event.inputs.packageVersion }}

      - name: Update Package Version
        run: |
          sed -i "s/version: .*/version: ${{ github.event.inputs.packageVersion }}/" pubspec.yaml

      - name: Update Library Version in download script
        run: |
          sed -i '/VERSION=/!b;cVERSION=\"v${{ github.event.inputs.libraryVersion }}";' ./download-libs.sh

      - name: Commit, Tag and Push
        run: |
          git add pubspec.yaml
          git add download-libs.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "chore(package version): updated version" || exit 0
          git tag ${{ github.event.inputs.packageVersion }}
          git push --set-upstream origin release/${{ github.event.inputs.packageVersion }} 
          git push --tags
